# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_qori', models.CharField(max_length=250)),
                ('juz', models.CharField(max_length=500)),
                ('jenis', models.CharField(max_length=100)),
                ('gambar', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Murotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('surah', models.CharField(max_length=250)),
                ('qori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.Qori')),
            ],
        ),
    ]
