# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='murotal',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
