# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_murotal_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qori',
            name='gambar',
            field=models.FileField(upload_to=''),
        ),
    ]
