# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quran', '0003_auto_20171009_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murotal',
            name='file_type',
        ),
        migrations.AddField(
            model_name='qori',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qori',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='murotal',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
